### ISSUE TITLE
Add "terminal-recording" topic to this repo

### ISSUE THREAD

**Issue by katrinleinweber** [dhobsd/castty#32]
As an educator, I'd like to be able to advertise the concept of creating animations from the terminal. Thus, I like to link to https://github.com/topics/terminal-recording instead of collecting several tool links.

How about `castty` joins the small club and also adds the topic `terminal-recording` to this repo?

**Comment by dhobsd** [comment]
Done, thank you!

**Comment by katrinleinweber** [comment]
You're welcome :-)
